### ISSUE TITLE
AssertionError: Image shapes are differnet: (80, 120, 3), (320, 480, 3)

### ISSUE THREAD

**Issue by bobozy1999** [megvii-research/TLC#13]
Thanks for your enjoy！

I have a try in Rain100L dataset of my own trained net, but when calculating PSNR and SSIM, it gives me " AssertionError: Image shapes are differnet: (80, 120, 3), (320, 480, 3)". The size of my train test is (320,480). 

Look for your reply,thank you!

**Comment by achusky** [comment]
Hi, thanks for your interest for this repo.

Based on the information you provided, I suspect that the output of the model is 1/4 of the test image. You need to check the `scale` setting in config (e.g., [scale=1 for deblurring](https://github.com/megvii-research/TLC/blob/main/options/test/GoPro/RestormerLocal-GoPro.yml#L10)). You may set `scale=4` (need to be 1) so that the input images are downsampled by 4x. If you can provide more information it would be very helpful for me to debug. 

If my answer didn't solve your problem, feel free to ask again and I will contact you with WeChat.

**Comment by bobozy1999** [comment]
> Hi, thanks for your interest for this repo.
> 
> Based on the information you provided, I suspect that the output of the model is 1/4 of the test image. You need to check the `scale` setting in config (e.g., [scale=1 for deblurring](https://github.com/megvii-research/TLC/blob/main/options/test/GoPro/RestormerLocal-GoPro.yml#L10)). You may set `scale=4` (need to be 1) so that the input images are downsampled by 4x. If you can provide more information it would be very helpful for me to debug.
> 
> If my answer didn't solve your problem, feel free to ask again and I will contact you with WeChat.
“AssertionError: Image shapes are differnet: (80, 120, 3), (320, 480, 3).”
我把sclae设置成了1或者4，都会出现了以上的error
